spring.application.name=pagos
server.port=9093

# Conexión a tu BD en el puerto 3307
spring.datasource.url=jdbc:mysql://localhost:3306/db_pagos?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Magia de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false