services:

  ms-eureka:
    build: ./ms-eureka
    container_name: ms-eureka
    ports:
      - "8761:8761"

  inventory:
    build: ./inventario
    container_name: inventory
    ports:
      - "9096:9096"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - ms-eureka

  catalogo:
    build: ./catalogo
    container_name: catalogo
    ports:
      - "9095:9095"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - ms-eureka
      
  carro:
    build: ./carro
    container_name: carro
    ports:
      - "9098:9098"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - ms-eureka
      
  usuarios:
    build: ./usuarios
    container_name: usuarios
    ports:
      - "9091:9091"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - ms-eureka
   
  autenticacion:
    build: ./autenticacion
    container_name: autenticacion
    ports:
      - "9092:9092"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - ms-eureka

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - ms-eureka
      - autenticacion