server:
  port: 9090

spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://ms-eureka:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO