server:
  port: 9090

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      routes:
        - id: catalogo-service
          uri: lb://catalogo
          predicates:
            - Path=/api/v1/catalogo/**
            
        - id: pedidos-service
          uri: lb://pedidos
          predicates:
            - Path=/api/v1/pedidos/**
            
        - id: usuarios-service
          uri: lb://usuarios
          predicates:
            - Path=/api/v1/usuarios/**
            
        - id: pagos-service
          uri: lb://pagos
          predicates:
            - Path=/api/v1/pagos/**
            
        - id: carro-service
          uri: lb://carro
          predicates:
            - Path=/api/v1/carro/**

        - id: busqueda-service
          uri: lb://busqueda
          predicates:
            - Path=/api/v1/busqueda/**

        - id: envios-service
          uri: lb://envios
          predicates:
              - Path=/api/v1/envios/**

        - id: inventario-service
          uri: lb://inventory
          predicates:
              - Path=/api/v1/inventory/**

        - id: autenticacion-service
          uri: lb://autenticacion
          predicates:
              - Path=/api/v1/auth/**

        - id: notificaciones-service
          uri: lb://notificaciones
          predicates:
              - Path=/api/v1/notificaciones/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka