spring.application.name=inventory
# ¡Crucial! El Carrito lo va a buscar en este puerto exacto:
server.port=8082

# Conexión a la base de datos exclusiva del inventario
spring.datasource.url=jdbc:mysql://localhost:3307/inventory_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Dejamos "update" para que Spring cree la tabla por ti
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true