spring.application.name=notificaciones
server.port=9094

# Credenciales y URL
spring.datasource.url=jdbc:mysql://localhost:3307/marketplace_notificaciones?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Forzamos el Driver y el Dialecto para que Spring no se confunda
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true